
namespace Multicare_pharmacy.Forms
{
    partial class SalesPanel
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties121 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties122 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties123 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties124 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties125 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties126 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties127 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties128 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties129 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties130 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties131 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties132 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties133 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties134 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties135 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties136 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SalesPanel));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties113 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties114 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties115 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties116 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties117 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties118 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties119 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties120 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties137 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties138 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties139 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties140 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties141 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties142 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties143 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties144 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.productID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tabQuanCb = new System.Windows.Forms.CheckBox();
            this.packs = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tabQuantity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.amountRecieved = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel6 = new System.Windows.Forms.TableLayoutPanel();
            this.cardRB = new System.Windows.Forms.RadioButton();
            this.cashRB = new System.Windows.Forms.RadioButton();
            this.generateBill = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.detailsDGV = new System.Windows.Forms.DataGridView();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.CID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.sessionCode = new Bunifu.UI.WinForms.BunifuLabel();
            this.getDetailsBTN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addCustBTN = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.grandTotal = new Bunifu.UI.WinForms.BunifuLabel();
            this.employeeID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.totalProducts = new Bunifu.UI.WinForms.BunifuLabel();
            this.employeeName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel6.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDGV)).BeginInit();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel4, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel5, 0, 2);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 3;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.60745F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 87.39255F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 46F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(816, 444);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 2;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 75.52534F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24.47466F));
            this.tableLayoutPanel2.Controls.Add(this.tableLayoutPanel3, 1, 0);
            this.tableLayoutPanel2.Controls.Add(this.detailsDGV, 0, 0);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 53);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 1;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(810, 341);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.productID, 0, 0);
            this.tableLayoutPanel3.Controls.Add(this.tabQuanCb, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.packs, 0, 2);
            this.tableLayoutPanel3.Controls.Add(this.tabQuantity, 0, 3);
            this.tableLayoutPanel3.Controls.Add(this.amountRecieved, 0, 4);
            this.tableLayoutPanel3.Controls.Add(this.tableLayoutPanel6, 0, 5);
            this.tableLayoutPanel3.Controls.Add(this.generateBill, 0, 6);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(614, 3);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 7;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 15.77381F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.79762F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(193, 335);
            this.tableLayoutPanel3.TabIndex = 0;
            // 
            // productID
            // 
            this.productID.AcceptsReturn = false;
            this.productID.AcceptsTab = false;
            this.productID.AnimationSpeed = 200;
            this.productID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.productID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.productID.BackColor = System.Drawing.Color.White;
            this.productID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("productID.BackgroundImage")));
            this.productID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.productID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.productID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.productID.BorderColorIdle = System.Drawing.Color.Silver;
            this.productID.BorderRadius = 1;
            this.productID.BorderThickness = 1;
            this.productID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.productID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.productID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.productID.DefaultText = "";
            this.productID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.productID.FillColor = System.Drawing.Color.White;
            this.productID.HideSelection = true;
            this.productID.IconLeft = null;
            this.productID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.productID.IconPadding = 10;
            this.productID.IconRight = null;
            this.productID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.productID.Lines = new string[0];
            this.productID.Location = new System.Drawing.Point(3, 3);
            this.productID.MaxLength = 32767;
            this.productID.MinimumSize = new System.Drawing.Size(1, 1);
            this.productID.Modified = false;
            this.productID.Multiline = false;
            this.productID.Name = "productID";
            stateProperties121.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties121.FillColor = System.Drawing.Color.Empty;
            stateProperties121.ForeColor = System.Drawing.Color.Empty;
            stateProperties121.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productID.OnActiveState = stateProperties121;
            stateProperties122.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties122.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties122.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties122.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.productID.OnDisabledState = stateProperties122;
            stateProperties123.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties123.FillColor = System.Drawing.Color.Empty;
            stateProperties123.ForeColor = System.Drawing.Color.Empty;
            stateProperties123.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productID.OnHoverState = stateProperties123;
            stateProperties124.BorderColor = System.Drawing.Color.Silver;
            stateProperties124.FillColor = System.Drawing.Color.White;
            stateProperties124.ForeColor = System.Drawing.Color.Empty;
            stateProperties124.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.productID.OnIdleState = stateProperties124;
            this.productID.Padding = new System.Windows.Forms.Padding(3);
            this.productID.PasswordChar = '\0';
            this.productID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.productID.PlaceholderText = "Product ID";
            this.productID.ReadOnly = false;
            this.productID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.productID.SelectedText = "";
            this.productID.SelectionLength = 0;
            this.productID.SelectionStart = 0;
            this.productID.ShortcutsEnabled = true;
            this.productID.Size = new System.Drawing.Size(187, 41);
            this.productID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.productID.TabIndex = 2;
            this.productID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.productID.TextMarginBottom = 0;
            this.productID.TextMarginLeft = 3;
            this.productID.TextMarginTop = 0;
            this.productID.TextPlaceholder = "Product ID";
            this.productID.UseSystemPasswordChar = false;
            this.productID.WordWrap = true;
            // 
            // tabQuanCb
            // 
            this.tabQuanCb.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabQuanCb.AutoSize = true;
            this.tabQuanCb.Location = new System.Drawing.Point(3, 50);
            this.tabQuanCb.Name = "tabQuanCb";
            this.tabQuanCb.Size = new System.Drawing.Size(187, 41);
            this.tabQuanCb.TabIndex = 4;
            this.tabQuanCb.Text = "Quantity";
            this.tabQuanCb.UseVisualStyleBackColor = true;
            this.tabQuanCb.CheckedChanged += new System.EventHandler(this.TabQuan_CheckedChanged);
            // 
            // packs
            // 
            this.packs.AcceptsReturn = false;
            this.packs.AcceptsTab = false;
            this.packs.AnimationSpeed = 200;
            this.packs.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.packs.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.packs.BackColor = System.Drawing.Color.White;
            this.packs.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("packs.BackgroundImage")));
            this.packs.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.packs.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.packs.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.packs.BorderColorIdle = System.Drawing.Color.Silver;
            this.packs.BorderRadius = 1;
            this.packs.BorderThickness = 1;
            this.packs.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.packs.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.packs.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.packs.DefaultText = "";
            this.packs.Dock = System.Windows.Forms.DockStyle.Fill;
            this.packs.FillColor = System.Drawing.Color.White;
            this.packs.HideSelection = true;
            this.packs.IconLeft = null;
            this.packs.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.packs.IconPadding = 10;
            this.packs.IconRight = null;
            this.packs.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.packs.Lines = new string[0];
            this.packs.Location = new System.Drawing.Point(3, 97);
            this.packs.MaxLength = 32767;
            this.packs.MinimumSize = new System.Drawing.Size(1, 1);
            this.packs.Modified = false;
            this.packs.Multiline = false;
            this.packs.Name = "packs";
            stateProperties125.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties125.FillColor = System.Drawing.Color.Empty;
            stateProperties125.ForeColor = System.Drawing.Color.Empty;
            stateProperties125.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.packs.OnActiveState = stateProperties125;
            stateProperties126.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties126.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties126.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties126.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.packs.OnDisabledState = stateProperties126;
            stateProperties127.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties127.FillColor = System.Drawing.Color.Empty;
            stateProperties127.ForeColor = System.Drawing.Color.Empty;
            stateProperties127.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.packs.OnHoverState = stateProperties127;
            stateProperties128.BorderColor = System.Drawing.Color.Silver;
            stateProperties128.FillColor = System.Drawing.Color.White;
            stateProperties128.ForeColor = System.Drawing.Color.Empty;
            stateProperties128.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.packs.OnIdleState = stateProperties128;
            this.packs.Padding = new System.Windows.Forms.Padding(3);
            this.packs.PasswordChar = '\0';
            this.packs.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.packs.PlaceholderText = "Number of Packs";
            this.packs.ReadOnly = false;
            this.packs.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.packs.SelectedText = "";
            this.packs.SelectionLength = 0;
            this.packs.SelectionStart = 0;
            this.packs.ShortcutsEnabled = true;
            this.packs.Size = new System.Drawing.Size(187, 41);
            this.packs.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.packs.TabIndex = 3;
            this.packs.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.packs.TextMarginBottom = 0;
            this.packs.TextMarginLeft = 3;
            this.packs.TextMarginTop = 0;
            this.packs.TextPlaceholder = "Number of Packs";
            this.packs.UseSystemPasswordChar = false;
            this.packs.WordWrap = true;
            this.packs.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tabQuantity_KeyDown);
            // 
            // tabQuantity
            // 
            this.tabQuantity.AcceptsReturn = false;
            this.tabQuantity.AcceptsTab = false;
            this.tabQuantity.AnimationSpeed = 200;
            this.tabQuantity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tabQuantity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tabQuantity.BackColor = System.Drawing.Color.White;
            this.tabQuantity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tabQuantity.BackgroundImage")));
            this.tabQuantity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tabQuantity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tabQuantity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tabQuantity.BorderColorIdle = System.Drawing.Color.Silver;
            this.tabQuantity.BorderRadius = 1;
            this.tabQuantity.BorderThickness = 1;
            this.tabQuantity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tabQuantity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tabQuantity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.tabQuantity.DefaultText = "";
            this.tabQuantity.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabQuantity.FillColor = System.Drawing.Color.White;
            this.tabQuantity.HideSelection = true;
            this.tabQuantity.IconLeft = null;
            this.tabQuantity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tabQuantity.IconPadding = 10;
            this.tabQuantity.IconRight = null;
            this.tabQuantity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tabQuantity.Lines = new string[0];
            this.tabQuantity.Location = new System.Drawing.Point(3, 144);
            this.tabQuantity.MaxLength = 32767;
            this.tabQuantity.MinimumSize = new System.Drawing.Size(1, 1);
            this.tabQuantity.Modified = false;
            this.tabQuantity.Multiline = false;
            this.tabQuantity.Name = "tabQuantity";
            stateProperties129.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties129.FillColor = System.Drawing.Color.Empty;
            stateProperties129.ForeColor = System.Drawing.Color.Empty;
            stateProperties129.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tabQuantity.OnActiveState = stateProperties129;
            stateProperties130.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties130.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties130.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties130.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tabQuantity.OnDisabledState = stateProperties130;
            stateProperties131.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties131.FillColor = System.Drawing.Color.Empty;
            stateProperties131.ForeColor = System.Drawing.Color.Empty;
            stateProperties131.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tabQuantity.OnHoverState = stateProperties131;
            stateProperties132.BorderColor = System.Drawing.Color.Silver;
            stateProperties132.FillColor = System.Drawing.Color.White;
            stateProperties132.ForeColor = System.Drawing.Color.Empty;
            stateProperties132.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tabQuantity.OnIdleState = stateProperties132;
            this.tabQuantity.Padding = new System.Windows.Forms.Padding(3);
            this.tabQuantity.PasswordChar = '\0';
            this.tabQuantity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tabQuantity.PlaceholderText = "Tablets Quantity";
            this.tabQuantity.ReadOnly = false;
            this.tabQuantity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tabQuantity.SelectedText = "";
            this.tabQuantity.SelectionLength = 0;
            this.tabQuantity.SelectionStart = 0;
            this.tabQuantity.ShortcutsEnabled = true;
            this.tabQuantity.Size = new System.Drawing.Size(187, 41);
            this.tabQuantity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.tabQuantity.TabIndex = 5;
            this.tabQuantity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tabQuantity.TextMarginBottom = 0;
            this.tabQuantity.TextMarginLeft = 3;
            this.tabQuantity.TextMarginTop = 0;
            this.tabQuantity.TextPlaceholder = "Tablets Quantity";
            this.tabQuantity.UseSystemPasswordChar = false;
            this.tabQuantity.WordWrap = true;
            this.tabQuantity.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tabQuantity_KeyDown);
            // 
            // amountRecieved
            // 
            this.amountRecieved.AcceptsReturn = false;
            this.amountRecieved.AcceptsTab = false;
            this.amountRecieved.AnimationSpeed = 200;
            this.amountRecieved.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.amountRecieved.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.amountRecieved.BackColor = System.Drawing.Color.White;
            this.amountRecieved.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("amountRecieved.BackgroundImage")));
            this.amountRecieved.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.amountRecieved.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.amountRecieved.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.amountRecieved.BorderColorIdle = System.Drawing.Color.Silver;
            this.amountRecieved.BorderRadius = 1;
            this.amountRecieved.BorderThickness = 1;
            this.amountRecieved.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.amountRecieved.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.amountRecieved.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.amountRecieved.DefaultText = "";
            this.amountRecieved.Dock = System.Windows.Forms.DockStyle.Fill;
            this.amountRecieved.FillColor = System.Drawing.Color.White;
            this.amountRecieved.HideSelection = true;
            this.amountRecieved.IconLeft = null;
            this.amountRecieved.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountRecieved.IconPadding = 10;
            this.amountRecieved.IconRight = null;
            this.amountRecieved.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountRecieved.Lines = new string[0];
            this.amountRecieved.Location = new System.Drawing.Point(3, 191);
            this.amountRecieved.MaxLength = 32767;
            this.amountRecieved.MinimumSize = new System.Drawing.Size(1, 1);
            this.amountRecieved.Modified = false;
            this.amountRecieved.Multiline = false;
            this.amountRecieved.Name = "amountRecieved";
            stateProperties133.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties133.FillColor = System.Drawing.Color.Empty;
            stateProperties133.ForeColor = System.Drawing.Color.Empty;
            stateProperties133.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountRecieved.OnActiveState = stateProperties133;
            stateProperties134.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties134.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties134.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties134.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.amountRecieved.OnDisabledState = stateProperties134;
            stateProperties135.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties135.FillColor = System.Drawing.Color.Empty;
            stateProperties135.ForeColor = System.Drawing.Color.Empty;
            stateProperties135.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountRecieved.OnHoverState = stateProperties135;
            stateProperties136.BorderColor = System.Drawing.Color.Silver;
            stateProperties136.FillColor = System.Drawing.Color.White;
            stateProperties136.ForeColor = System.Drawing.Color.Empty;
            stateProperties136.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountRecieved.OnIdleState = stateProperties136;
            this.amountRecieved.Padding = new System.Windows.Forms.Padding(3);
            this.amountRecieved.PasswordChar = '\0';
            this.amountRecieved.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.amountRecieved.PlaceholderText = "Amount Recieved";
            this.amountRecieved.ReadOnly = false;
            this.amountRecieved.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.amountRecieved.SelectedText = "";
            this.amountRecieved.SelectionLength = 0;
            this.amountRecieved.SelectionStart = 0;
            this.amountRecieved.ShortcutsEnabled = true;
            this.amountRecieved.Size = new System.Drawing.Size(187, 41);
            this.amountRecieved.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.amountRecieved.TabIndex = 6;
            this.amountRecieved.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.amountRecieved.TextMarginBottom = 0;
            this.amountRecieved.TextMarginLeft = 3;
            this.amountRecieved.TextMarginTop = 0;
            this.amountRecieved.TextPlaceholder = "Amount Recieved";
            this.amountRecieved.UseSystemPasswordChar = false;
            this.amountRecieved.WordWrap = true;
            // 
            // tableLayoutPanel6
            // 
            this.tableLayoutPanel6.ColumnCount = 1;
            this.tableLayoutPanel6.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.Controls.Add(this.cardRB, 0, 0);
            this.tableLayoutPanel6.Controls.Add(this.cashRB, 0, 1);
            this.tableLayoutPanel6.Location = new System.Drawing.Point(3, 238);
            this.tableLayoutPanel6.Name = "tableLayoutPanel6";
            this.tableLayoutPanel6.RowCount = 2;
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel6.Size = new System.Drawing.Size(187, 46);
            this.tableLayoutPanel6.TabIndex = 7;
            // 
            // cardRB
            // 
            this.cardRB.AutoSize = true;
            this.cardRB.Location = new System.Drawing.Point(3, 3);
            this.cardRB.Name = "cardRB";
            this.cardRB.Size = new System.Drawing.Size(47, 17);
            this.cardRB.TabIndex = 0;
            this.cardRB.TabStop = true;
            this.cardRB.Text = "Card";
            this.cardRB.UseVisualStyleBackColor = true;
            // 
            // cashRB
            // 
            this.cashRB.AutoSize = true;
            this.cashRB.Location = new System.Drawing.Point(3, 26);
            this.cashRB.Name = "cashRB";
            this.cashRB.Size = new System.Drawing.Size(49, 17);
            this.cashRB.TabIndex = 1;
            this.cashRB.TabStop = true;
            this.cashRB.Text = "Cash";
            this.cashRB.UseVisualStyleBackColor = true;
            // 
            // generateBill
            // 
            this.generateBill.AllowAnimations = true;
            this.generateBill.AllowMouseEffects = true;
            this.generateBill.AllowToggling = false;
            this.generateBill.AnimationSpeed = 200;
            this.generateBill.AutoGenerateColors = false;
            this.generateBill.AutoRoundBorders = false;
            this.generateBill.AutoSizeLeftIcon = true;
            this.generateBill.AutoSizeRightIcon = true;
            this.generateBill.BackColor = System.Drawing.Color.Transparent;
            this.generateBill.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.generateBill.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("generateBill.BackgroundImage")));
            this.generateBill.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.generateBill.ButtonText = "Generate Bill";
            this.generateBill.ButtonTextMarginLeft = 0;
            this.generateBill.ColorContrastOnClick = 45;
            this.generateBill.ColorContrastOnHover = 45;
            this.generateBill.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.generateBill.CustomizableEdges = borderEdges12;
            this.generateBill.DialogResult = System.Windows.Forms.DialogResult.None;
            this.generateBill.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.generateBill.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.generateBill.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.generateBill.Dock = System.Windows.Forms.DockStyle.Fill;
            this.generateBill.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.generateBill.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.generateBill.ForeColor = System.Drawing.Color.White;
            this.generateBill.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.generateBill.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.generateBill.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.generateBill.IconMarginLeft = 11;
            this.generateBill.IconPadding = 10;
            this.generateBill.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.generateBill.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.generateBill.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.generateBill.IconSize = 25;
            this.generateBill.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.generateBill.IdleBorderRadius = 1;
            this.generateBill.IdleBorderThickness = 1;
            this.generateBill.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.generateBill.IdleIconLeftImage = null;
            this.generateBill.IdleIconRightImage = null;
            this.generateBill.IndicateFocus = false;
            this.generateBill.Location = new System.Drawing.Point(3, 290);
            this.generateBill.Name = "generateBill";
            this.generateBill.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.generateBill.OnDisabledState.BorderRadius = 1;
            this.generateBill.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.generateBill.OnDisabledState.BorderThickness = 1;
            this.generateBill.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.generateBill.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.generateBill.OnDisabledState.IconLeftImage = null;
            this.generateBill.OnDisabledState.IconRightImage = null;
            this.generateBill.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.generateBill.onHoverState.BorderRadius = 1;
            this.generateBill.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.generateBill.onHoverState.BorderThickness = 1;
            this.generateBill.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.generateBill.onHoverState.ForeColor = System.Drawing.Color.White;
            this.generateBill.onHoverState.IconLeftImage = null;
            this.generateBill.onHoverState.IconRightImage = null;
            this.generateBill.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.generateBill.OnIdleState.BorderRadius = 1;
            this.generateBill.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.generateBill.OnIdleState.BorderThickness = 1;
            this.generateBill.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.generateBill.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.generateBill.OnIdleState.IconLeftImage = null;
            this.generateBill.OnIdleState.IconRightImage = null;
            this.generateBill.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.generateBill.OnPressedState.BorderRadius = 1;
            this.generateBill.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.generateBill.OnPressedState.BorderThickness = 1;
            this.generateBill.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.generateBill.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.generateBill.OnPressedState.IconLeftImage = null;
            this.generateBill.OnPressedState.IconRightImage = null;
            this.generateBill.Size = new System.Drawing.Size(187, 42);
            this.generateBill.TabIndex = 8;
            this.generateBill.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.generateBill.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.generateBill.TextMarginLeft = 0;
            this.generateBill.TextPadding = new System.Windows.Forms.Padding(0);
            this.generateBill.UseDefaultRadiusAndThickness = true;
            this.generateBill.Click += new System.EventHandler(this.generateBillBTN_Click);
            // 
            // detailsDGV
            // 
            this.detailsDGV.AllowUserToAddRows = false;
            this.detailsDGV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.detailsDGV.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.detailsDGV.Dock = System.Windows.Forms.DockStyle.Fill;
            this.detailsDGV.Location = new System.Drawing.Point(3, 3);
            this.detailsDGV.Name = "detailsDGV";
            this.detailsDGV.Size = new System.Drawing.Size(605, 335);
            this.detailsDGV.TabIndex = 1;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 6;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 24.59827F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12.97899F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 12.23733F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.66667F));
            this.tableLayoutPanel4.Controls.Add(this.CID, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.sessionCode, 5, 0);
            this.tableLayoutPanel4.Controls.Add(this.getDetailsBTN, 3, 0);
            this.tableLayoutPanel4.Controls.Add(this.CAddress, 2, 0);
            this.tableLayoutPanel4.Controls.Add(this.addCustBTN, 4, 0);
            this.tableLayoutPanel4.Controls.Add(this.CName, 1, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(810, 44);
            this.tableLayoutPanel4.TabIndex = 1;
            // 
            // CID
            // 
            this.CID.AcceptsReturn = false;
            this.CID.AcceptsTab = false;
            this.CID.AnimationSpeed = 200;
            this.CID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CID.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CID.BackgroundImage")));
            this.CID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CID.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CID.BorderRadius = 1;
            this.CID.BorderThickness = 1;
            this.CID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.CID.DefaultText = "";
            this.CID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CID.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CID.ForeColor = System.Drawing.SystemColors.ControlText;
            this.CID.HideSelection = true;
            this.CID.IconLeft = null;
            this.CID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CID.IconPadding = 10;
            this.CID.IconRight = null;
            this.CID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CID.Lines = new string[0];
            this.CID.Location = new System.Drawing.Point(3, 3);
            this.CID.MaxLength = 32767;
            this.CID.MinimumSize = new System.Drawing.Size(1, 1);
            this.CID.Modified = false;
            this.CID.Multiline = false;
            this.CID.Name = "CID";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CID.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CID.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CID.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties112.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties112.ForeColor = System.Drawing.SystemColors.ControlText;
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.CID.OnIdleState = stateProperties112;
            this.CID.Padding = new System.Windows.Forms.Padding(3);
            this.CID.PasswordChar = '\0';
            this.CID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CID.PlaceholderText = "Customer ID";
            this.CID.ReadOnly = false;
            this.CID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CID.SelectedText = "";
            this.CID.SelectionLength = 0;
            this.CID.SelectionStart = 0;
            this.CID.ShortcutsEnabled = true;
            this.CID.Size = new System.Drawing.Size(129, 38);
            this.CID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.CID.TabIndex = 0;
            this.CID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CID.TextMarginBottom = 0;
            this.CID.TextMarginLeft = 3;
            this.CID.TextMarginTop = 0;
            this.CID.TextPlaceholder = "Customer ID";
            this.CID.UseSystemPasswordChar = false;
            this.CID.WordWrap = true;
            // 
            // sessionCode
            // 
            this.sessionCode.AllowParentOverrides = false;
            this.sessionCode.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.sessionCode.AutoEllipsis = false;
            this.sessionCode.Cursor = System.Windows.Forms.Cursors.Default;
            this.sessionCode.CursorType = System.Windows.Forms.Cursors.Default;
            this.sessionCode.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.sessionCode.ForeColor = System.Drawing.Color.Black;
            this.sessionCode.Location = new System.Drawing.Point(676, 3);
            this.sessionCode.Name = "sessionCode";
            this.sessionCode.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.sessionCode.Size = new System.Drawing.Size(101, 21);
            this.sessionCode.TabIndex = 3;
            this.sessionCode.Text = "bunifuLabel1";
            this.sessionCode.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.sessionCode.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // getDetailsBTN
            // 
            this.getDetailsBTN.AllowAnimations = true;
            this.getDetailsBTN.AllowMouseEffects = true;
            this.getDetailsBTN.AllowToggling = false;
            this.getDetailsBTN.AnimationSpeed = 200;
            this.getDetailsBTN.AutoGenerateColors = false;
            this.getDetailsBTN.AutoRoundBorders = false;
            this.getDetailsBTN.AutoSizeLeftIcon = true;
            this.getDetailsBTN.AutoSizeRightIcon = true;
            this.getDetailsBTN.BackColor = System.Drawing.Color.Transparent;
            this.getDetailsBTN.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.getDetailsBTN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("getDetailsBTN.BackgroundImage")));
            this.getDetailsBTN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.getDetailsBTN.ButtonText = "Get Details";
            this.getDetailsBTN.ButtonTextMarginLeft = 0;
            this.getDetailsBTN.ColorContrastOnClick = 45;
            this.getDetailsBTN.ColorContrastOnHover = 45;
            this.getDetailsBTN.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.getDetailsBTN.CustomizableEdges = borderEdges10;
            this.getDetailsBTN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.getDetailsBTN.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.getDetailsBTN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.getDetailsBTN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.getDetailsBTN.Dock = System.Windows.Forms.DockStyle.Fill;
            this.getDetailsBTN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.getDetailsBTN.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.getDetailsBTN.ForeColor = System.Drawing.Color.White;
            this.getDetailsBTN.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.getDetailsBTN.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.getDetailsBTN.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.getDetailsBTN.IconMarginLeft = 11;
            this.getDetailsBTN.IconPadding = 10;
            this.getDetailsBTN.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.getDetailsBTN.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.getDetailsBTN.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.getDetailsBTN.IconSize = 25;
            this.getDetailsBTN.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.getDetailsBTN.IdleBorderRadius = 1;
            this.getDetailsBTN.IdleBorderThickness = 1;
            this.getDetailsBTN.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.getDetailsBTN.IdleIconLeftImage = null;
            this.getDetailsBTN.IdleIconRightImage = null;
            this.getDetailsBTN.IndicateFocus = false;
            this.getDetailsBTN.Location = new System.Drawing.Point(472, 3);
            this.getDetailsBTN.Name = "getDetailsBTN";
            this.getDetailsBTN.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.getDetailsBTN.OnDisabledState.BorderRadius = 1;
            this.getDetailsBTN.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.getDetailsBTN.OnDisabledState.BorderThickness = 1;
            this.getDetailsBTN.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.getDetailsBTN.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.getDetailsBTN.OnDisabledState.IconLeftImage = null;
            this.getDetailsBTN.OnDisabledState.IconRightImage = null;
            this.getDetailsBTN.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.getDetailsBTN.onHoverState.BorderRadius = 1;
            this.getDetailsBTN.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.getDetailsBTN.onHoverState.BorderThickness = 1;
            this.getDetailsBTN.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.getDetailsBTN.onHoverState.ForeColor = System.Drawing.Color.White;
            this.getDetailsBTN.onHoverState.IconLeftImage = null;
            this.getDetailsBTN.onHoverState.IconRightImage = null;
            this.getDetailsBTN.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.getDetailsBTN.OnIdleState.BorderRadius = 1;
            this.getDetailsBTN.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.getDetailsBTN.OnIdleState.BorderThickness = 1;
            this.getDetailsBTN.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.getDetailsBTN.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.getDetailsBTN.OnIdleState.IconLeftImage = null;
            this.getDetailsBTN.OnIdleState.IconRightImage = null;
            this.getDetailsBTN.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.getDetailsBTN.OnPressedState.BorderRadius = 1;
            this.getDetailsBTN.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.getDetailsBTN.OnPressedState.BorderThickness = 1;
            this.getDetailsBTN.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.getDetailsBTN.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.getDetailsBTN.OnPressedState.IconLeftImage = null;
            this.getDetailsBTN.OnPressedState.IconRightImage = null;
            this.getDetailsBTN.Size = new System.Drawing.Size(99, 38);
            this.getDetailsBTN.TabIndex = 10;
            this.getDetailsBTN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.getDetailsBTN.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.getDetailsBTN.TextMarginLeft = 0;
            this.getDetailsBTN.TextPadding = new System.Windows.Forms.Padding(0);
            this.getDetailsBTN.UseDefaultRadiusAndThickness = true;
            this.getDetailsBTN.Click += new System.EventHandler(this.getDetailsBTN_Click);
            // 
            // CAddress
            // 
            this.CAddress.AcceptsReturn = false;
            this.CAddress.AcceptsTab = false;
            this.CAddress.AnimationSpeed = 200;
            this.CAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CAddress.BackColor = System.Drawing.Color.White;
            this.CAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CAddress.BackgroundImage")));
            this.CAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.CAddress.BorderRadius = 1;
            this.CAddress.BorderThickness = 1;
            this.CAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.CAddress.DefaultText = "";
            this.CAddress.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CAddress.Enabled = false;
            this.CAddress.FillColor = System.Drawing.Color.White;
            this.CAddress.HideSelection = true;
            this.CAddress.IconLeft = null;
            this.CAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CAddress.IconPadding = 10;
            this.CAddress.IconRight = null;
            this.CAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CAddress.Lines = new string[0];
            this.CAddress.Location = new System.Drawing.Point(273, 3);
            this.CAddress.MaxLength = 32767;
            this.CAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.CAddress.Modified = false;
            this.CAddress.Multiline = false;
            this.CAddress.Name = "CAddress";
            stateProperties113.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties113.FillColor = System.Drawing.Color.Empty;
            stateProperties113.ForeColor = System.Drawing.Color.Empty;
            stateProperties113.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CAddress.OnActiveState = stateProperties113;
            stateProperties114.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties114.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties114.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties114.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CAddress.OnDisabledState = stateProperties114;
            stateProperties115.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties115.FillColor = System.Drawing.Color.Empty;
            stateProperties115.ForeColor = System.Drawing.Color.Empty;
            stateProperties115.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CAddress.OnHoverState = stateProperties115;
            stateProperties116.BorderColor = System.Drawing.Color.Silver;
            stateProperties116.FillColor = System.Drawing.Color.White;
            stateProperties116.ForeColor = System.Drawing.Color.Empty;
            stateProperties116.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CAddress.OnIdleState = stateProperties116;
            this.CAddress.Padding = new System.Windows.Forms.Padding(3);
            this.CAddress.PasswordChar = '\0';
            this.CAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CAddress.PlaceholderText = "Customer Address";
            this.CAddress.ReadOnly = false;
            this.CAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CAddress.SelectedText = "";
            this.CAddress.SelectionLength = 0;
            this.CAddress.SelectionStart = 0;
            this.CAddress.ShortcutsEnabled = true;
            this.CAddress.Size = new System.Drawing.Size(193, 38);
            this.CAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.CAddress.TabIndex = 2;
            this.CAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CAddress.TextMarginBottom = 0;
            this.CAddress.TextMarginLeft = 3;
            this.CAddress.TextMarginTop = 0;
            this.CAddress.TextPlaceholder = "Customer Address";
            this.CAddress.UseSystemPasswordChar = false;
            this.CAddress.WordWrap = true;
            // 
            // addCustBTN
            // 
            this.addCustBTN.AllowAnimations = true;
            this.addCustBTN.AllowMouseEffects = true;
            this.addCustBTN.AllowToggling = false;
            this.addCustBTN.AnimationSpeed = 200;
            this.addCustBTN.AutoGenerateColors = false;
            this.addCustBTN.AutoRoundBorders = false;
            this.addCustBTN.AutoSizeLeftIcon = true;
            this.addCustBTN.AutoSizeRightIcon = true;
            this.addCustBTN.BackColor = System.Drawing.Color.Transparent;
            this.addCustBTN.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.addCustBTN.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addCustBTN.BackgroundImage")));
            this.addCustBTN.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addCustBTN.ButtonText = "Add Customer";
            this.addCustBTN.ButtonTextMarginLeft = 0;
            this.addCustBTN.ColorContrastOnClick = 45;
            this.addCustBTN.ColorContrastOnHover = 45;
            this.addCustBTN.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.addCustBTN.CustomizableEdges = borderEdges11;
            this.addCustBTN.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addCustBTN.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addCustBTN.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addCustBTN.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addCustBTN.Dock = System.Windows.Forms.DockStyle.Fill;
            this.addCustBTN.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addCustBTN.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.addCustBTN.ForeColor = System.Drawing.Color.White;
            this.addCustBTN.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addCustBTN.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addCustBTN.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addCustBTN.IconMarginLeft = 11;
            this.addCustBTN.IconPadding = 10;
            this.addCustBTN.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addCustBTN.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addCustBTN.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addCustBTN.IconSize = 25;
            this.addCustBTN.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.addCustBTN.IdleBorderRadius = 1;
            this.addCustBTN.IdleBorderThickness = 1;
            this.addCustBTN.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.addCustBTN.IdleIconLeftImage = null;
            this.addCustBTN.IdleIconRightImage = null;
            this.addCustBTN.IndicateFocus = false;
            this.addCustBTN.Location = new System.Drawing.Point(577, 3);
            this.addCustBTN.Name = "addCustBTN";
            this.addCustBTN.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addCustBTN.OnDisabledState.BorderRadius = 1;
            this.addCustBTN.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addCustBTN.OnDisabledState.BorderThickness = 1;
            this.addCustBTN.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addCustBTN.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addCustBTN.OnDisabledState.IconLeftImage = null;
            this.addCustBTN.OnDisabledState.IconRightImage = null;
            this.addCustBTN.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addCustBTN.onHoverState.BorderRadius = 1;
            this.addCustBTN.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addCustBTN.onHoverState.BorderThickness = 1;
            this.addCustBTN.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addCustBTN.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addCustBTN.onHoverState.IconLeftImage = null;
            this.addCustBTN.onHoverState.IconRightImage = null;
            this.addCustBTN.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.addCustBTN.OnIdleState.BorderRadius = 1;
            this.addCustBTN.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addCustBTN.OnIdleState.BorderThickness = 1;
            this.addCustBTN.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.addCustBTN.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addCustBTN.OnIdleState.IconLeftImage = null;
            this.addCustBTN.OnIdleState.IconRightImage = null;
            this.addCustBTN.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addCustBTN.OnPressedState.BorderRadius = 1;
            this.addCustBTN.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addCustBTN.OnPressedState.BorderThickness = 1;
            this.addCustBTN.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addCustBTN.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addCustBTN.OnPressedState.IconLeftImage = null;
            this.addCustBTN.OnPressedState.IconRightImage = null;
            this.addCustBTN.Size = new System.Drawing.Size(93, 38);
            this.addCustBTN.TabIndex = 9;
            this.addCustBTN.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addCustBTN.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addCustBTN.TextMarginLeft = 0;
            this.addCustBTN.TextPadding = new System.Windows.Forms.Padding(0);
            this.addCustBTN.UseDefaultRadiusAndThickness = true;
            this.addCustBTN.Click += new System.EventHandler(this.addCustBTN_Click);
            // 
            // CName
            // 
            this.CName.AcceptsReturn = false;
            this.CName.AcceptsTab = false;
            this.CName.AnimationSpeed = 200;
            this.CName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CName.BackColor = System.Drawing.Color.White;
            this.CName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CName.BackgroundImage")));
            this.CName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CName.BorderColorIdle = System.Drawing.Color.Silver;
            this.CName.BorderRadius = 1;
            this.CName.BorderThickness = 1;
            this.CName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.CName.DefaultText = "";
            this.CName.Dock = System.Windows.Forms.DockStyle.Fill;
            this.CName.Enabled = false;
            this.CName.FillColor = System.Drawing.Color.White;
            this.CName.HideSelection = true;
            this.CName.IconLeft = null;
            this.CName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CName.IconPadding = 10;
            this.CName.IconRight = null;
            this.CName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CName.Lines = new string[0];
            this.CName.Location = new System.Drawing.Point(138, 3);
            this.CName.MaxLength = 32767;
            this.CName.MinimumSize = new System.Drawing.Size(1, 1);
            this.CName.Modified = false;
            this.CName.Multiline = false;
            this.CName.Name = "CName";
            stateProperties117.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties117.FillColor = System.Drawing.Color.Empty;
            stateProperties117.ForeColor = System.Drawing.Color.Empty;
            stateProperties117.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CName.OnActiveState = stateProperties117;
            stateProperties118.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties118.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties118.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties118.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CName.OnDisabledState = stateProperties118;
            stateProperties119.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties119.FillColor = System.Drawing.Color.Empty;
            stateProperties119.ForeColor = System.Drawing.Color.Empty;
            stateProperties119.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CName.OnHoverState = stateProperties119;
            stateProperties120.BorderColor = System.Drawing.Color.Silver;
            stateProperties120.FillColor = System.Drawing.Color.White;
            stateProperties120.ForeColor = System.Drawing.Color.Empty;
            stateProperties120.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CName.OnIdleState = stateProperties120;
            this.CName.Padding = new System.Windows.Forms.Padding(3);
            this.CName.PasswordChar = '\0';
            this.CName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.CName.PlaceholderText = "Customer Name";
            this.CName.ReadOnly = false;
            this.CName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CName.SelectedText = "";
            this.CName.SelectionLength = 0;
            this.CName.SelectionStart = 0;
            this.CName.ShortcutsEnabled = true;
            this.CName.Size = new System.Drawing.Size(129, 38);
            this.CName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.CName.TabIndex = 1;
            this.CName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CName.TextMarginBottom = 0;
            this.CName.TextMarginLeft = 3;
            this.CName.TextMarginTop = 0;
            this.CName.TextPlaceholder = "Customer Name";
            this.CName.UseSystemPasswordChar = false;
            this.CName.WordWrap = true;
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 4;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.tableLayoutPanel5.Controls.Add(this.bunifuLabel1, 0, 1);
            this.tableLayoutPanel5.Controls.Add(this.grandTotal, 0, 0);
            this.tableLayoutPanel5.Controls.Add(this.employeeID, 2, 0);
            this.tableLayoutPanel5.Controls.Add(this.employeeName, 3, 0);
            this.tableLayoutPanel5.Controls.Add(this.totalProducts, 1, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(3, 400);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 2;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 0F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(810, 41);
            this.tableLayoutPanel5.TabIndex = 2;
            // 
            // grandTotal
            // 
            this.grandTotal.AllowParentOverrides = false;
            this.grandTotal.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.grandTotal.AutoEllipsis = false;
            this.grandTotal.Cursor = System.Windows.Forms.Cursors.Default;
            this.grandTotal.CursorType = System.Windows.Forms.Cursors.Default;
            this.grandTotal.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.grandTotal.ForeColor = System.Drawing.Color.Black;
            this.grandTotal.Location = new System.Drawing.Point(3, 3);
            this.grandTotal.Name = "grandTotal";
            this.grandTotal.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.grandTotal.Size = new System.Drawing.Size(106, 21);
            this.grandTotal.TabIndex = 4;
            this.grandTotal.Text = "Grand Total: 0";
            this.grandTotal.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.grandTotal.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // employeeID
            // 
            this.employeeID.AcceptsReturn = false;
            this.employeeID.AcceptsTab = false;
            this.employeeID.AnimationSpeed = 200;
            this.employeeID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.employeeID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.employeeID.BackColor = System.Drawing.Color.White;
            this.employeeID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("employeeID.BackgroundImage")));
            this.employeeID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.employeeID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeeID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.employeeID.BorderColorIdle = System.Drawing.Color.Silver;
            this.employeeID.BorderRadius = 1;
            this.employeeID.BorderThickness = 1;
            this.employeeID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.employeeID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeID.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.employeeID.DefaultText = "";
            this.employeeID.Dock = System.Windows.Forms.DockStyle.Fill;
            this.employeeID.Enabled = false;
            this.employeeID.FillColor = System.Drawing.Color.White;
            this.employeeID.HideSelection = true;
            this.employeeID.IconLeft = null;
            this.employeeID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeID.IconPadding = 10;
            this.employeeID.IconRight = null;
            this.employeeID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeID.Lines = new string[0];
            this.employeeID.Location = new System.Drawing.Point(407, 3);
            this.employeeID.MaxLength = 32767;
            this.employeeID.MinimumSize = new System.Drawing.Size(1, 1);
            this.employeeID.Modified = false;
            this.employeeID.Multiline = false;
            this.employeeID.Name = "employeeID";
            stateProperties137.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties137.FillColor = System.Drawing.Color.Empty;
            stateProperties137.ForeColor = System.Drawing.Color.Empty;
            stateProperties137.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeID.OnActiveState = stateProperties137;
            stateProperties138.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties138.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties138.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties138.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.employeeID.OnDisabledState = stateProperties138;
            stateProperties139.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties139.FillColor = System.Drawing.Color.Empty;
            stateProperties139.ForeColor = System.Drawing.Color.Empty;
            stateProperties139.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeID.OnHoverState = stateProperties139;
            stateProperties140.BorderColor = System.Drawing.Color.Silver;
            stateProperties140.FillColor = System.Drawing.Color.White;
            stateProperties140.ForeColor = System.Drawing.Color.Empty;
            stateProperties140.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeID.OnIdleState = stateProperties140;
            this.employeeID.Padding = new System.Windows.Forms.Padding(3);
            this.employeeID.PasswordChar = '\0';
            this.employeeID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.employeeID.PlaceholderText = "Employee ID";
            this.employeeID.ReadOnly = false;
            this.employeeID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.employeeID.SelectedText = "";
            this.employeeID.SelectionLength = 0;
            this.employeeID.SelectionStart = 0;
            this.employeeID.ShortcutsEnabled = true;
            this.employeeID.Size = new System.Drawing.Size(196, 35);
            this.employeeID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.employeeID.TabIndex = 6;
            this.employeeID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.employeeID.TextMarginBottom = 0;
            this.employeeID.TextMarginLeft = 3;
            this.employeeID.TextMarginTop = 0;
            this.employeeID.TextPlaceholder = "Employee ID";
            this.employeeID.UseSystemPasswordChar = false;
            this.employeeID.WordWrap = true;
            // 
            // totalProducts
            // 
            this.totalProducts.AllowParentOverrides = false;
            this.totalProducts.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.totalProducts.AutoEllipsis = false;
            this.totalProducts.Cursor = System.Windows.Forms.Cursors.Default;
            this.totalProducts.CursorType = System.Windows.Forms.Cursors.Default;
            this.totalProducts.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.totalProducts.ForeColor = System.Drawing.Color.Black;
            this.totalProducts.Location = new System.Drawing.Point(205, 3);
            this.totalProducts.Name = "totalProducts";
            this.totalProducts.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.totalProducts.Size = new System.Drawing.Size(127, 21);
            this.totalProducts.TabIndex = 5;
            this.totalProducts.Text = "Total Products: 0";
            this.totalProducts.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.totalProducts.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // employeeName
            // 
            this.employeeName.AcceptsReturn = false;
            this.employeeName.AcceptsTab = false;
            this.employeeName.AnimationSpeed = 200;
            this.employeeName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.employeeName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.employeeName.BackColor = System.Drawing.Color.White;
            this.employeeName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("employeeName.BackgroundImage")));
            this.employeeName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.employeeName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.employeeName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.employeeName.BorderColorIdle = System.Drawing.Color.Silver;
            this.employeeName.BorderRadius = 1;
            this.employeeName.BorderThickness = 1;
            this.employeeName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.employeeName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.employeeName.DefaultText = "";
            this.employeeName.Dock = System.Windows.Forms.DockStyle.Fill;
            this.employeeName.Enabled = false;
            this.employeeName.FillColor = System.Drawing.Color.White;
            this.employeeName.HideSelection = true;
            this.employeeName.IconLeft = null;
            this.employeeName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeName.IconPadding = 10;
            this.employeeName.IconRight = null;
            this.employeeName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.employeeName.Lines = new string[0];
            this.employeeName.Location = new System.Drawing.Point(609, 3);
            this.employeeName.MaxLength = 32767;
            this.employeeName.MinimumSize = new System.Drawing.Size(1, 1);
            this.employeeName.Modified = false;
            this.employeeName.Multiline = false;
            this.employeeName.Name = "employeeName";
            stateProperties141.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties141.FillColor = System.Drawing.Color.Empty;
            stateProperties141.ForeColor = System.Drawing.Color.Empty;
            stateProperties141.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeName.OnActiveState = stateProperties141;
            stateProperties142.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties142.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties142.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties142.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.employeeName.OnDisabledState = stateProperties142;
            stateProperties143.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties143.FillColor = System.Drawing.Color.Empty;
            stateProperties143.ForeColor = System.Drawing.Color.Empty;
            stateProperties143.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeName.OnHoverState = stateProperties143;
            stateProperties144.BorderColor = System.Drawing.Color.Silver;
            stateProperties144.FillColor = System.Drawing.Color.White;
            stateProperties144.ForeColor = System.Drawing.Color.Empty;
            stateProperties144.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.employeeName.OnIdleState = stateProperties144;
            this.employeeName.Padding = new System.Windows.Forms.Padding(3);
            this.employeeName.PasswordChar = '\0';
            this.employeeName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.employeeName.PlaceholderText = "Employee Name";
            this.employeeName.ReadOnly = false;
            this.employeeName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.employeeName.SelectedText = "";
            this.employeeName.SelectionLength = 0;
            this.employeeName.SelectionStart = 0;
            this.employeeName.ShortcutsEnabled = true;
            this.employeeName.Size = new System.Drawing.Size(198, 35);
            this.employeeName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.employeeName.TabIndex = 7;
            this.employeeName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.employeeName.TextMarginBottom = 0;
            this.employeeName.TextMarginLeft = 3;
            this.employeeName.TextMarginTop = 0;
            this.employeeName.TextPlaceholder = "Employee Name";
            this.employeeName.UseSystemPasswordChar = false;
            this.employeeName.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
            | System.Windows.Forms.AnchorStyles.Left)));
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(3, 44);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(106, 21);
            this.bunifuLabel1.TabIndex = 8;
            this.bunifuLabel1.Text = "Grand Total: 0";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // SalesPanel
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(816, 444);
            this.Controls.Add(this.tableLayoutPanel1);
            this.MaximumSize = new System.Drawing.Size(832, 483);
            this.MinimumSize = new System.Drawing.Size(832, 483);
            this.Name = "SalesPanel";
            this.Text = "Sales Panel";
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel3.PerformLayout();
            this.tableLayoutPanel6.ResumeLayout(false);
            this.tableLayoutPanel6.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.detailsDGV)).EndInit();
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel4.PerformLayout();
            this.tableLayoutPanel5.ResumeLayout(false);
            this.tableLayoutPanel5.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private Bunifu.UI.WinForms.BunifuTextBox CID;
        private Bunifu.UI.WinForms.BunifuTextBox CName;
        private Bunifu.UI.WinForms.BunifuTextBox CAddress;
        private Bunifu.UI.WinForms.BunifuLabel sessionCode;
        private System.Windows.Forms.DataGridView detailsDGV;
        private Bunifu.UI.WinForms.BunifuTextBox productID;
        private Bunifu.UI.WinForms.BunifuTextBox packs;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private Bunifu.UI.WinForms.BunifuLabel grandTotal;
        private System.Windows.Forms.CheckBox tabQuanCb;
        private Bunifu.UI.WinForms.BunifuTextBox tabQuantity;
        private Bunifu.UI.WinForms.BunifuTextBox employeeID;
        private Bunifu.UI.WinForms.BunifuTextBox amountRecieved;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel6;
        private System.Windows.Forms.RadioButton cardRB;
        private System.Windows.Forms.RadioButton cashRB;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton generateBill;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton getDetailsBTN;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addCustBTN;
        private Bunifu.UI.WinForms.BunifuTextBox employeeName;
        private Bunifu.UI.WinForms.BunifuLabel totalProducts;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}